/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.espe.edu.view;

/**
 *
 * @author jorge
 */
public class FrmPrincipalMenu extends javax.swing.JFrame {

    private String name;

    /**
     * Creates new form FrmPrincipalMenu
     */
    public FrmPrincipalMenu() {
        this.name = "";
        initComponents();
    }

    public FrmPrincipalMenu(String name) {
        this.name = name;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuAttendance = new javax.swing.JMenu();
        itmMarkAttendance = new javax.swing.JMenuItem();
        itmViewAttendanceHistory = new javax.swing.JMenuItem();
        itmPenalty = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itmRegister = new javax.swing.JMenuItem();
        itmFilter = new javax.swing.JMenuItem();
        itmReport = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        ItmMnuPersonalInventory = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Craft Market logo");

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        mnuAttendance.setText("Asistencia");

        itmMarkAttendance.setText("Marcar Asistencia");
        itmMarkAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMarkAttendanceActionPerformed(evt);
            }
        });
        mnuAttendance.add(itmMarkAttendance);

        itmViewAttendanceHistory.setText("Ver historial de asistencia");
        itmViewAttendanceHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmViewAttendanceHistoryActionPerformed(evt);
            }
        });
        mnuAttendance.add(itmViewAttendanceHistory);

        itmPenalty.setText("Penalización");
        itmPenalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPenaltyActionPerformed(evt);
            }
        });
        mnuAttendance.add(itmPenalty);

        jMenuBar1.add(mnuAttendance);

        jMenu3.setText("Ventas");

        itmRegister.setText("Registrar venta");
        itmRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegisterActionPerformed(evt);
            }
        });
        jMenu3.add(itmRegister);

        itmFilter.setText("Buscar venta por fecha");
        itmFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmFilterActionPerformed(evt);
            }
        });
        jMenu3.add(itmFilter);

        itmReport.setText("Reporte mensual");
        itmReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmReportActionPerformed(evt);
            }
        });
        jMenu3.add(itmReport);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Inventario");

        jMenuItem8.setText("Inventario general");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        ItmMnuPersonalInventory.setText("Inventario personal");
        ItmMnuPersonalInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmMnuPersonalInventoryActionPerformed(evt);
            }
        });
        jMenu4.add(ItmMnuPersonalInventory);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Productos");

        jMenuItem10.setText("Añadir producto");
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Editar producto");
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Borrar producto");
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itmRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegisterActionPerformed
        // TODO add your handling code here:
        FrmRegisterSale frmRegisterSale = new FrmRegisterSale();
        frmRegisterSale.setVisible(true);
        frmRegisterSale.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_itmRegisterActionPerformed

    private void itmMarkAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMarkAttendanceActionPerformed
        String artisanUsername = name;
        FrmMarkAttendence frmMarkAttendence = new FrmMarkAttendence(artisanUsername);
        frmMarkAttendence.setVisible(true);
        frmMarkAttendence.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_itmMarkAttendanceActionPerformed

    private void itmFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmFilterActionPerformed
        // TODO add your handling code here:
        FrmFilterByDate frmFilterByDate = new FrmFilterByDate();
        frmFilterByDate.setVisible(true);
        frmFilterByDate.setLocationRelativeTo(null);
    }//GEN-LAST:event_itmFilterActionPerformed

    private void itmReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmReportActionPerformed
        // TODO add your handling code here:
        FrmMonthlyReport frmMonthlyReport = new FrmMonthlyReport();
        frmMonthlyReport.setVisible(true);
        frmMonthlyReport.setLocationRelativeTo(null);
    }//GEN-LAST:event_itmReportActionPerformed

    private void itmViewAttendanceHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmViewAttendanceHistoryActionPerformed
         String artisanUsername = name;
        FrmCheckAttendanceHistory frmCheckAttendanceHistory  =new FrmCheckAttendanceHistory(artisanUsername);
         frmCheckAttendanceHistory.setVisible(true); 
        frmCheckAttendanceHistory.setLocationRelativeTo(null);
         this.dispose();
    }//GEN-LAST:event_itmViewAttendanceHistoryActionPerformed

    private void itmPenaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPenaltyActionPerformed
       String artisanUsername = name;
        FrmPenalty frmPenalty =new FrmPenalty(artisanUsername);
         frmPenalty.setVisible(true); 
        frmPenalty.setLocationRelativeTo(null);
         this.dispose();
    }//GEN-LAST:event_itmPenaltyActionPerformed

    private void ItmMnuPersonalInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmMnuPersonalInventoryActionPerformed
        // TODO add your handling code here:
        FrmPersonalInventory frmPersonalInventory = new FrmPersonalInventory();
        frmPersonalInventory.setVisible(true);
        setVisible(false);
       
    }//GEN-LAST:event_ItmMnuPersonalInventoryActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        FrmGeneralInventory frmGeneralInventory = new FrmGeneralInventory();
        frmGeneralInventory.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalMenu("hla").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItmMnuPersonalInventory;
    private javax.swing.JMenuItem itmFilter;
    private javax.swing.JMenuItem itmMarkAttendance;
    private javax.swing.JMenuItem itmPenalty;
    private javax.swing.JMenuItem itmRegister;
    private javax.swing.JMenuItem itmReport;
    private javax.swing.JMenuItem itmViewAttendanceHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu mnuAttendance;
    // End of variables declaration//GEN-END:variables
}
